apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname']
      receiver: 'default'

    receivers:
      - name: 'default'
        email_configs:
          - to: your-email@example.com
            from: noreply@example.com
            smarthost: smtp.gmail.com:587
            auth_username: uar0405@gmail.com
            auth_password: your-app-password

